server:
  port: 8080

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true # false 로 해도됨.
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
#        - id: user-server
#          uri: lb://USER-SERVER # loadBalancing
#          predicates:
#            - Path=/user/**
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/welcome
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment} # test 용
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-server
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter # 로그인,회원 가입 제외하고는 authorizationHeaderFilter 적용!(token 써야한다)

        - id: portfolio-server
          uri: lb://PORTFOLIO-SERVER
          predicates:
            - Path=/portfolio/**

        - id: wallet-write-server
          uri: lb://WALLET-WRITE-SERVER
          predicates:
            - Path=/walletwrite/**

token:
  secret: user_token